name: Docker
on:
    push:
        tags:
            - "v*"
    pull_request:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
    id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run tests
              run: npm run ci:test

            - name: Publish coveralls report
              uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e #2.3.7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker meta
              id: docker_meta
              uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 #v6.2.0
              with:
                  images: |
                      name=ghcr.io/cartesi/rollups-explorer-api
                      name=docker.io/cartesi/rollups-explorer-api,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
                  tags: |
                      type=semver,pattern={{version}}
                      type=ref,event=branch
                      type=ref,event=pr

            - name: Login to Docker Hub
              uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 #v4.4.0
              if: ${{ startsWith(github.ref, 'refs/tags/v') }}
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 #v4.4.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Depot
              uses: depot/setup-action@15c09a5f77a0840ad4bce955686522a257853461 #1.7.1

            - name: Build and push docker image
              id: docker_build
              uses: depot/bake-action@1d58c2668346981089b088b7ef36755b206b20e9 #1.13.0
              with:
                  files: |
                      ./docker-bake.hcl
                      ./docker-bake.platforms.hcl
                      cwd://${{ steps.docker_meta.outputs.bake-file }}
                  push: true
                  project: ${{ vars.DEPOT_PROJECT }}
